import { CalendarDays, ChevronDown, MoreVertical, Plus } from 'lucide-react';
import { useMemo, useState } from 'react';
import { BarraNavegacion } from '@/componentes/BarraNavegacion';
import { FormularioMovimiento } from '@/componentes/FormularioMovimiento';
import { PanelConsejos } from '@/componentes/PanelConsejos';
import { PanelMetas } from '@/componentes/PanelMetas';
import { PanelPrestamos } from '@/componentes/PanelPrestamos';
import { SeccionFlujoCaja } from '@/componentes/SeccionFlujoCaja';
import { TablaMovimientos } from '@/componentes/TablaMovimientos';
import { TarjetasResumen } from '@/componentes/TarjetasResumen';
import { cargarMovimientos, crearMovimiento, guardarMovimientos } from '@/datos/movimientos';
import { Movimiento, TipoMovimiento } from '@/tipos/movimientos';

export function PaginaPrincipal() { const [movimientos, setMovimientos] = useState<Movimiento[]>(cargarMovimientos); const [modalAbierto, setModalAbierto] = useState(false); const [busqueda, setBusqueda] = useState(''); const [filtroTipo, setFiltroTipo] = useState<'todos' | TipoMovimiento>('todos');
  const resumen = useMemo(() => { const ingresos = movimientos.filter((item) => item.tipo === 'ingreso').reduce((total, item) => total + item.monto, 0); const gastos = movimientos.filter((item) => item.tipo === 'gasto').reduce((total, item) => total + item.monto, 0); const prestamos = movimientos.filter((item) => item.tipo === 'prestamo').reduce((total, item) => total + item.monto, 0); return { ingresos, gastos, prestamos, ahorro: ingresos - gastos, proyectado: ingresos - gastos - prestamos }; }, [movimientos]);
  const movimientosFiltrados = movimientos.filter((item) => `${item.nota} ${item.categoria} ${item.cuenta}`.toLowerCase().includes(busqueda.toLowerCase()) && (filtroTipo === 'todos' || item.tipo === filtroTipo)).sort((a, b) => b.fecha.localeCompare(a.fecha));
  function agregarMovimiento(datos: Omit<Movimiento, 'id'>) { const nuevos = [crearMovimiento(datos), ...movimientos]; setMovimientos(nuevos); guardarMovimientos(nuevos); setModalAbierto(false); }
  function exportarMovimientos() { const filas = [['Fecha', 'Tipo', 'Concepto', 'Categoría', 'Cuenta', 'Monto'], ...movimientosFiltrados.map((item) => [item.fecha, item.tipo, item.nota, item.categoria, item.cuenta, item.monto.toFixed(2)])]; const contenido = filas.map((fila) => fila.map((celda) => `"${celda.replace(/"/g, '""')}"`).join(';')).join('\n'); const enlace = document.createElement('a'); enlace.href = URL.createObjectURL(new Blob([`\ufeff${contenido}`], { type: 'text/csv;charset=utf-8;' })); enlace.download = 'movimientos-financieros.csv'; enlace.click(); URL.revokeObjectURL(enlace.href); }
  return <div className="min-h-screen bg-[#f8f7fb] text-[#1d1d26]"><BarraNavegacion onExportar={exportarMovimientos} onNuevoMovimiento={() => setModalAbierto(true)} /><main id="inicio" className="mx-auto max-w-[1440px] space-y-5 px-5 py-7 lg:px-10 lg:py-9"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1 text-xs font-semibold uppercase tracking-[.12em] text-[#777887]">15 de noviembre de 2024</p><h1 className="text-[28px] font-bold tracking-[-.7px]">Resumen general</h1><p className="mt-1 text-sm text-[#6f7080]">Tu salud financiera de la quincena actual.</p></div><div className="flex items-center gap-2"><button className="flex items-center gap-2 rounded-lg border border-[#d5d4df] bg-white px-3 py-2 text-xs font-semibold text-[#555766]"><CalendarDays size={15} /> Esta quincena <ChevronDown size={14} /></button><button className="hidden rounded-lg p-2 text-[#777887] hover:bg-white sm:block" aria-label="Más opciones"><MoreVertical size={19} /></button></div></div><TarjetasResumen resumen={resumen} /><div className="grid gap-5 xl:grid-cols-[minmax(0,2fr)_minmax(300px,1fr)]"><SeccionFlujoCaja resumen={resumen} /><PanelConsejos gastos={resumen.gastos} /></div><div className="grid items-start gap-5 xl:grid-cols-[minmax(0,2fr)_minmax(300px,1fr)]"><TablaMovimientos movimientos={movimientosFiltrados} busqueda={busqueda} filtroTipo={filtroTipo} onBusqueda={setBusqueda} onFiltro={setFiltroTipo} onExportar={exportarMovimientos} /><div className="space-y-5"><PanelMetas /><PanelPrestamos prestamos={resumen.prestamos} /></div></div></main><button onClick={() => setModalAbierto(true)} className="fixed bottom-6 right-6 grid h-14 w-14 place-items-center rounded-full bg-[#293ea9] text-white shadow-xl shadow-[#293ea9]/30 transition hover:scale-105 sm:hidden" aria-label="Registrar movimiento"><Plus size={25} /></button>{modalAbierto && <FormularioMovimiento alCerrar={() => setModalAbierto(false)} alGuardar={agregarMovimiento} />}</div>; }
