import { Bell, Download, Menu, Plus, Wallet } from 'lucide-react';
import { useState } from 'react';

type Props = { onExportar: () => void; onNuevoMovimiento: () => void };

export function BarraNavegacion({ onExportar, onNuevoMovimiento }: Props) {
  const [menuAbierto, setMenuAbierto] = useState(false);
  return <header className="sticky top-0 z-30 border-b border-[#dddde8] bg-white/95 backdrop-blur"><div className="mx-auto flex h-[72px] max-w-[1440px] items-center gap-8 px-5 lg:px-10"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#293ea9] text-white shadow-lg shadow-[#293ea9]/20"><Wallet size={21} /></div><span className="text-[25px] font-bold tracking-[-1px] text-[#293ea9]">FinanzPro</span></div><nav className="hidden items-center gap-8 text-[13px] font-semibold text-[#6f7080] md:flex"><a className="border-b-2 border-[#293ea9] py-7 text-[#293ea9]" href="#inicio">Dashboard</a><a href="#movimientos" className="hover:text-[#293ea9]">Presupuesto</a><a href="#metas" className="hover:text-[#293ea9]">Inversiones</a><a href="#reportes" className="hover:text-[#293ea9]">Reportes</a></nav><div className="ml-auto flex items-center gap-3"><button onClick={onExportar} className="hidden h-10 items-center gap-2 rounded-lg border border-[#293ea9] px-4 text-xs font-bold text-[#293ea9] transition hover:bg-[#eef0ff] sm:flex"><Download size={15} /> Exportar a Excel</button><button onClick={onNuevoMovimiento} className="hidden h-10 items-center gap-2 rounded-lg bg-[#293ea9] px-5 text-xs font-bold text-white shadow-md shadow-[#293ea9]/20 transition hover:bg-[#1e308e] sm:flex"><Plus size={16} /> Registrar movimiento</button><button className="rounded-full p-2 text-[#555766] hover:bg-[#f0f0f6]" aria-label="Notificaciones"><Bell size={19} /></button><div className="grid h-9 w-9 place-items-center rounded-full bg-[#dfe7f4] text-sm font-bold text-[#293ea9]">AM</div><button onClick={() => setMenuAbierto(!menuAbierto)} className="rounded-lg p-2 md:hidden" aria-label="Abrir menú"><Menu size={20} /></button></div></div>{menuAbierto && <div className="border-t border-[#e4e3eb] bg-white p-4 md:hidden"><div className="grid gap-3 text-sm font-semibold text-[#545665]"><a href="#inicio">Dashboard</a><a href="#movimientos">Movimientos</a><button onClick={onNuevoMovimiento} className="flex items-center gap-2 text-left text-[#293ea9]"><Plus size={16} /> Registrar movimiento</button></div></div>}</header>;
}
