import { FormEvent, useState } from 'react';
import { CalendarClock, X } from 'lucide-react';
import { Cuenta, FrecuenciaRecurrente, GastoRecurrente } from '@/tipos/movimientos';

type Props = { recurrente?: GastoRecurrente; cuentas: Cuenta[]; alCerrar: () => void; alGuardar: (datos: Omit<GastoRecurrente, 'id' | 'user_id'>) => Promise<void> };

export function FormularioRecurrente({ recurrente, cuentas, alCerrar, alGuardar }: Props) {
  const [nombre, setNombre] = useState(recurrente?.nombre ?? '');
  const [tipo, setTipo] = useState<'gasto' | 'ingreso'>(recurrente?.tipo ?? 'gasto');
  const [monto, setMonto] = useState(String(recurrente?.monto ?? ''));
  const [frecuencia, setFrecuencia] = useState<FrecuenciaRecurrente>(recurrente?.frecuencia ?? 'mensual');
  const [fecha, setFecha] = useState(recurrente?.fecha_proximo_cobro ?? new Date().toISOString().slice(0, 10));
  const [categoria, setCategoria] = useState(recurrente?.categoria ?? (tipo === 'ingreso' ? 'Sueldo' : 'Servicios'));
  const [cuentaId, setCuentaId] = useState(recurrente?.cuenta_id ?? cuentas[0]?.id ?? '');
  const [error, setError] = useState('');
  async function enviar(evento: FormEvent<HTMLFormElement>) { evento.preventDefault(); if (!nombre.trim() || Number(monto) <= 0 || !fecha || !cuentaId) { setError('Completa nombre, monto, fecha y cuenta.'); return; } await alGuardar({ nombre: nombre.trim(), monto: Number(monto), tipo, frecuencia, dia_cobro: null, fecha_proximo_cobro: fecha, categoria: categoria.trim() || null, cuenta_id: cuentaId, activo: recurrente?.activo ?? true }); }
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-[#1d1d26]/45 p-0 sm:items-center sm:p-4" role="dialog" aria-modal="true" onClick={alCerrar}><div className="w-full max-w-[560px] rounded-t-[22px] bg-white shadow-2xl sm:rounded-[22px]" onClick={(evento) => evento.stopPropagation()}><div className="flex items-center justify-between border-b px-5 py-4"><div className="flex items-center gap-3"><CalendarClock className="text-[#293ea9]" /><h2 className="text-lg font-bold">{recurrente ? 'Editar recurrente' : 'Nuevo recurrente'}</h2></div><button onClick={alCerrar} aria-label="Cerrar"><X size={20} /></button></div><form onSubmit={enviar} className="space-y-4 p-5"><Campo etiqueta="Tipo"><select value={tipo} onChange={(evento) => { const nuevoTipo = evento.target.value as 'gasto' | 'ingreso'; setTipo(nuevoTipo); setCategoria(nuevoTipo === 'ingreso' ? 'Sueldo' : 'Servicios'); }} className="campo"><option value="gasto">Gasto recurrente</option><option value="ingreso">Ingreso recurrente</option></select></Campo><Campo etiqueta="Nombre"><input required value={nombre} onChange={(evento) => setNombre(evento.target.value)} className="campo" placeholder="Ej. Sueldo, freelance o Spotify" /></Campo><div className="grid gap-4 sm:grid-cols-2"><Campo etiqueta="Monto"><input required type="number" min="0.01" step="0.01" value={monto} onChange={(evento) => setMonto(evento.target.value)} className="campo" /></Campo><Campo etiqueta="Frecuencia"><select value={frecuencia} onChange={(evento) => setFrecuencia(evento.target.value as FrecuenciaRecurrente)} className="campo"><option value="diario">Diario</option><option value="semanal">Semanal</option><option value="quincenal">Quincenal</option><option value="mensual">Mensual</option></select></Campo></div><div className="grid gap-4 sm:grid-cols-2"><Campo etiqueta="Próximo cobro"><input required type="date" value={fecha} onChange={(evento) => setFecha(evento.target.value)} className="campo" /></Campo><Campo etiqueta="Categoría"><select value={categoria} onChange={(evento) => setCategoria(evento.target.value)} className="campo">{tipo === 'ingreso' ? <><option>Sueldo</option><option>Quincena</option><option>Pago freelance</option><option>Ingreso regular</option></> : <><option>Servicios</option><option>Transporte</option><option>Entretenimiento</option><option>Otro</option></>}</select></Campo></div><Campo etiqueta="Cuenta"><select required value={cuentaId} onChange={(evento) => setCuentaId(evento.target.value)} className="campo"><option value="">Selecciona cuenta</option>{cuentas.map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</select></Campo>{error && <p className="text-xs text-[#b3262d]">{error}</p>}<button className="w-full rounded-lg bg-[#293ea9] px-3 py-3 text-sm font-bold text-white">Guardar recurrente</button></form></div></div>;
}
function Campo({ etiqueta, children }: { etiqueta: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-[#5c5c6b]">{etiqueta}</span>{children}</label>; }
