import { ArrowRightLeft, X } from 'lucide-react';
import { FormEvent, useMemo, useState } from 'react';
import { Cuenta } from '@/tipos/movimientos';

type Props = { cuentas: Cuenta[]; cuentaOrigenInicial?: string; alCerrar: () => void; alTransferir: (origen: string, destino: string, monto: number, concepto: string, fecha: string) => Promise<void> };

export function FormularioTransferencia({ cuentas, cuentaOrigenInicial, alCerrar, alTransferir }: Props) {
  const [origen, setOrigen] = useState(cuentaOrigenInicial ?? cuentas[0]?.id ?? '');
  const [destino, setDestino] = useState(cuentas.find((cuenta) => cuenta.id !== (cuentaOrigenInicial ?? cuentas[0]?.id))?.id ?? '');
  const [monto, setMonto] = useState('');
  const [concepto, setConcepto] = useState('');
  const [fecha, setFecha] = useState(new Date().toISOString().slice(0, 10));
  const [error, setError] = useState('');
  const cuentaActual = useMemo(() => cuentas.find((cuenta) => cuenta.id === origen), [cuentas, origen]);

  function cambiarOrigen(id: string) { setOrigen(id); if (destino === id) setDestino(cuentas.find((cuenta) => cuenta.id !== id)?.id ?? ''); }
  async function enviar(evento: FormEvent<HTMLFormElement>) { evento.preventDefault(); if (!origen || !destino || origen === destino) { setError('Selecciona cuentas de origen y destino diferentes.'); return; } if (Number(monto) <= 0) { setError('Ingresa un monto mayor que 0.'); return; } if (Number(monto) > (cuentaActual?.saldo ?? 0)) { setError(`Saldo insuficiente. Disponible: S/ ${(cuentaActual?.saldo ?? 0).toFixed(2)}.`); return; } setError(''); await alTransferir(origen, destino, Number(monto), concepto.trim(), fecha); }

  return <div className="animate-overlay-in fixed inset-0 z-50 flex items-end justify-center bg-[#1d1d26]/45 p-0 backdrop-blur-sm sm:items-center sm:p-4" role="dialog" aria-modal="true" onClick={alCerrar}><div className="animate-modal-in w-full max-w-[560px] rounded-t-[22px] bg-white shadow-2xl sm:rounded-[22px]" onClick={(evento) => evento.stopPropagation()}><div className="flex items-center justify-between border-b border-[#e9e8f0] px-5 py-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#eef0ff] text-[#293ea9]"><ArrowRightLeft size={19} /></div><h2 className="text-lg font-bold">Transferir entre cuentas</h2></div><button onClick={alCerrar} aria-label="Cerrar"><X size={20} /></button></div><form onSubmit={enviar} className="space-y-4 p-5"><Campo etiqueta="Cuenta origen"><select value={origen} onChange={(evento) => cambiarOrigen(evento.target.value)} className="campo">{cuentas.map((cuenta) => <option key={cuenta.id} value={cuenta.id}>{cuenta.nombre} · S/ {cuenta.saldo.toFixed(2)}</option>)}</select></Campo><div className="grid place-items-center text-[#293ea9]"><ArrowRightLeft size={20} /></div><Campo etiqueta="Cuenta destino"><select value={destino} onChange={(evento) => setDestino(evento.target.value)} className="campo">{cuentas.map((cuenta) => <option disabled={cuenta.id === origen} key={cuenta.id} value={cuenta.id}>{cuenta.nombre} · S/ {cuenta.saldo.toFixed(2)}</option>)}</select></Campo><div className="grid gap-4 sm:grid-cols-2"><Campo etiqueta="Monto"><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-sm text-[#777887]">S/</span><input required type="number" min="0.01" step="0.01" inputMode="decimal" value={monto} onChange={(evento) => setMonto(evento.target.value)} className="campo pl-10" /></div></Campo><Campo etiqueta="Fecha"><input required type="date" value={fecha} onChange={(evento) => setFecha(evento.target.value)} className="campo" /></Campo></div><Campo etiqueta="Concepto (opcional)"><input value={concepto} onChange={(evento) => setConcepto(evento.target.value)} className="campo" placeholder="Ej. Retiro cajero BCP, recarga Yape..." /></Campo>{error && <p className="rounded-xl bg-[#fff0f0] px-3 py-2 text-sm text-[#b3262d]">{error}</p>}<div className="flex justify-end gap-3"><button type="button" onClick={alCerrar} className="h-11 rounded-xl border px-5 text-sm font-semibold">Cancelar</button><button type="submit" className="h-11 rounded-xl bg-[#293ea9] px-5 text-sm font-bold text-white">Transferir</button></div></form></div></div>;
}
function Campo({ etiqueta, children }: { etiqueta: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-[#5c5c6b]">{etiqueta}</span>{children}</label>; }
