import { FormEvent, useState } from 'react';
import { CreditCard, X } from 'lucide-react';
import { TipoCuenta } from '@/tipos/movimientos';

type Props = { alCerrar: () => void; alGuardar: (datos: { nombre: string; tipo: TipoCuenta; saldo: number; saldo_ahorrado: number; color: string }) => Promise<void> };

export function FormularioCuenta({ alCerrar, alGuardar }: Props) {
  const [nombre, setNombre] = useState('');
  const [tipo, setTipo] = useState<TipoCuenta>('banco');
  const [saldo, setSaldo] = useState('0');
  const [error, setError] = useState('');
  async function enviar(evento: FormEvent<HTMLFormElement>) { evento.preventDefault(); const saldoInicial = Number(saldo); if (!nombre.trim()) { setError('Escribe un nombre para la cuenta.'); return; } if (!Number.isFinite(saldoInicial) || saldoInicial < 0) { setError('Ingresa un saldo inicial válido, igual o mayor que 0.'); return; } await alGuardar({ nombre: nombre.trim(), tipo, saldo: saldoInicial, saldo_ahorrado: 0, color: '#293ea9' }); }
  return <div className="animate-overlay-in fixed inset-0 z-50 flex items-end justify-center bg-[#1d1d26]/45 p-0 backdrop-blur-sm sm:items-center sm:p-4" role="dialog" aria-modal="true" onClick={alCerrar}><div className="animate-modal-in w-full max-w-[500px] rounded-t-[22px] bg-white shadow-2xl sm:rounded-[22px]" onClick={(evento) => evento.stopPropagation()}><div className="flex items-center justify-between border-b px-5 py-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#eef0ff] text-[#293ea9]"><CreditCard size={19} /></div><h2 className="text-lg font-bold">Agregar cuenta</h2></div><button onClick={alCerrar} aria-label="Cerrar"><X size={20} /></button></div><form onSubmit={enviar} className="space-y-4 p-5"><Campo etiqueta="Nombre"><input required value={nombre} onChange={(evento) => setNombre(evento.target.value)} className="campo" placeholder="Ej. Banco BCP" /></Campo><div className="grid gap-4 sm:grid-cols-2"><Campo etiqueta="Tipo"><select value={tipo} onChange={(evento) => setTipo(evento.target.value as TipoCuenta)} className="campo"><option value="efectivo">Efectivo</option><option value="yape">Yape</option><option value="plin">Plin</option><option value="sip">Sip</option><option value="banco">Banco</option></select></Campo><Campo etiqueta="Saldo inicial"><input required type="number" min="0" step="0.01" value={saldo} onChange={(evento) => setSaldo(evento.target.value)} className="campo" /><span className="mt-1 block text-[11px] text-[#858592]">Ingresa el saldo real que tienes hoy en esta billetera.</span></Campo></div>{error && <p className="rounded-xl bg-[#fff0f0] px-3 py-2 text-sm text-[#b3262d]">{error}</p>}<div className="flex justify-end gap-3"><button type="button" onClick={alCerrar} className="h-11 rounded-xl border px-5 text-sm font-semibold">Cancelar</button><button type="submit" className="h-11 rounded-xl bg-[#293ea9] px-5 text-sm font-bold text-white">Guardar cuenta</button></div></form></div></div>;
}
function Campo({ etiqueta, children }: { etiqueta: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-[#5c5c6b]">{etiqueta}</span>{children}</label>; }
