import { Dumbbell, Film, Music, Plus, Scissors, Trash2 } from 'lucide-react';
import { GastoRecurrente } from '@/tipos/movimientos';
import { moneda } from '@/utilidades/formato';

function iconoPara(nombre: string) { const clave = nombre.toLowerCase(); if (clave.includes('spotify')) return <Music size={18} />; if (clave.includes('netflix') || clave.includes('disney') || clave.includes('crunchyroll')) return <Film size={18} />; if (clave.includes('barber')) return <Scissors size={18} />; if (clave.includes('gimnas')) return <Dumbbell size={18} />; return <Music size={18} />; }
function proximaFecha(item: GastoRecurrente) { if (item.fecha_proximo_cobro) return new Date(`${item.fecha_proximo_cobro}T12:00:00`).toLocaleDateString('es-PE', { day: '2-digit', month: 'short', year: 'numeric' }).replace('.', ''); return 'Por definir'; }
function factorMensual(frecuencia: GastoRecurrente['frecuencia']) { return frecuencia === 'diario' ? 30 : frecuencia === 'semanal' ? 4 : frecuencia === 'quincenal' ? 2 : 1; }
function factorQuincena(frecuencia: GastoRecurrente['frecuencia']) { return frecuencia === 'diario' ? 15 : frecuencia === 'semanal' ? 2 : frecuencia === 'quincenal' ? 1 : 0.5; }

export function GastosRecurrentes({ recurrentes, onAgregar, onEditar, onPausar, onEliminar }: { recurrentes: GastoRecurrente[]; onAgregar: () => void; onEditar: (item: GastoRecurrente) => void; onPausar: (item: GastoRecurrente) => void; onEliminar: (id: string) => void }) {
  const activos = recurrentes.filter((item) => item.activo);
  const totalMensual = activos.reduce((total, item) => total + item.monto * factorMensual(item.frecuencia), 0);
  const totalQuincena = activos.reduce((total, item) => total + item.monto * factorQuincena(item.frecuencia), 0);
  return <section id="recurrentes" className="rounded-2xl border border-[#dedde8] bg-white p-5 shadow-[0_2px_8px_rgba(29,29,38,.04)]"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Gastos recurrentes</h2><p className="mt-1 text-xs text-[#878795]">{moneda(totalMensual)} al mes · {moneda(totalQuincena)} esta quincena</p></div><button onClick={onAgregar} className="flex items-center gap-2 rounded-lg bg-[#293ea9] px-3 py-2 text-xs font-bold text-white"><Plus size={15} /> Agregar</button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{recurrentes.map((item) => <article key={item.id} className="rounded-xl border border-[#e4e3ed] p-4 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-[#eef0ff] text-[#293ea9]">{iconoPara(item.nombre)}</div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${item.activo ? 'bg-[#e5fbf1] text-[#007c59]' : 'bg-[#f1f1f5] text-[#858592]'}`}>{item.activo ? 'Activo' : 'Pausado'}</span></div><p className="mt-3 font-semibold">{item.nombre}</p><p className="mt-1 text-xl font-bold">{moneda(item.monto)}</p><p className="mt-1 text-xs text-[#858592]">Próximo cobro: {proximaFecha(item)}</p><div className="mt-3 flex gap-2"><button onClick={() => onEditar(item)} className="rounded-lg border px-2 py-1 text-[11px] font-semibold">Editar</button><button onClick={() => onPausar(item)} className="rounded-lg border px-2 py-1 text-[11px] font-semibold">{item.activo ? 'Pausar' : 'Activar'}</button><button onClick={() => onEliminar(item.id)} className="rounded-lg p-1 text-[#c52c2f]" aria-label={`Eliminar ${item.nombre}`}><Trash2 size={15} /></button></div></article>)}</div>{recurrentes.length === 0 && <p className="py-6 text-center text-sm text-[#858592]">Aún no tienes gastos recurrentes.</p>}</section>;
}
