import { FormEvent, useState } from 'react';
import { Check, HandCoins, Pencil, Trash2, X } from 'lucide-react';
import { Cuenta, Prestamo } from '@/tipos/movimientos';
import { moneda } from '@/utilidades/formato';

type Props = { prestamos: Prestamo[]; cuentas: Cuenta[]; onPagar: (prestamo: Prestamo, cuentaId: string) => Promise<void>; onEditar: (id: string, datos: Pick<Prestamo, 'persona' | 'monto'>) => Promise<void>; onEliminar: (id: string) => Promise<void> };

export function PanelPrestamos({ prestamos, cuentas, onPagar, onEditar, onEliminar }: Props) {
  const [pago, setPago] = useState<Prestamo>(); const [edicion, setEdicion] = useState<Prestamo>();
  const pendientes = prestamos.filter((item) => !item.pagado); const historial = prestamos.filter((item) => item.pagado);
  return <section className="rounded-xl border border-[#dedde8] bg-white p-5 shadow-[0_2px_8px_rgba(29,29,38,.04)]"><h2 className="mb-5 flex items-center gap-2 text-lg font-bold"><HandCoins size={18} /> Préstamos familiares</h2><div className="grid gap-5 md:grid-cols-2"><Lista titulo="Me deben" items={pendientes.filter((item) => item.direccion === 'me_deben')} color="text-[#007c59]" onPagar={setPago} onEditar={setEdicion} onEliminar={onEliminar} /><Lista titulo="Yo debo" items={pendientes.filter((item) => item.direccion === 'yo_debo')} color="text-[#c52c2f]" onPagar={setPago} onEditar={setEdicion} onEliminar={onEliminar} /></div><details className="mt-5 border-t border-[#ecebf1] pt-4"><summary className="cursor-pointer text-sm font-bold text-[#656472]">Historial ({historial.length})</summary><div className="mt-3 space-y-2">{historial.map((item) => <div key={item.id} className="flex justify-between rounded-lg bg-[#f5f5f7] px-3 py-2 text-xs"><span>{item.persona}</span><span>{moneda(item.monto)} <b className="ml-2 rounded-full bg-[#dedee3] px-2 py-1 text-[10px]">Pagado</b></span></div>)}</div></details>{pago && <ModalPago prestamo={pago} cuentas={cuentas} onCerrar={() => setPago(undefined)} onConfirmar={async (id) => { await onPagar(pago, id); setPago(undefined); }} />}{edicion && <ModalEdicion prestamo={edicion} onCerrar={() => setEdicion(undefined)} onConfirmar={async (datos) => { await onEditar(edicion.id, datos); setEdicion(undefined); }} />}</section>;
}

function Lista({ titulo, items, color, onPagar, onEditar, onEliminar }: { titulo: string; items: Prestamo[]; color: string; onPagar: (item: Prestamo) => void; onEditar: (item: Prestamo) => void; onEliminar: (id: string) => Promise<void> }) { return <div><div className="mb-2 flex justify-between"><h3 className={`text-xs font-bold uppercase ${color}`}>{titulo}</h3><span className={`font-bold ${color}`}>{moneda(items.reduce((total, item) => total + item.monto, 0))}</span></div><div className="space-y-2">{items.map((item) => <div key={item.id} className="rounded-lg border border-[#e4e3ed] p-3"><div className="flex justify-between gap-3"><div><p className="font-semibold">{item.persona}</p><p className="mt-1 text-xs text-[#858592]">{item.fecha ?? 'Sin fecha'} · {moneda(item.monto)}</p></div><span className="rounded-full bg-[#fff4df] px-2 py-1 text-[10px] font-bold text-[#9a6410]">Pendiente</span></div><div className="mt-3 flex gap-2"><button onClick={() => onPagar(item)} className="flex items-center gap-1 rounded-lg bg-[#293ea9] px-2 py-1 text-[11px] font-semibold text-white"><Check size={13} /> Marcar como pagado</button><button onClick={() => onEditar(item)} aria-label="Editar préstamo" className="rounded-lg border p-1"><Pencil size={13} /></button><button onClick={() => void onEliminar(item.id)} aria-label="Eliminar préstamo" className="rounded-lg border p-1 text-[#c52c2f]"><Trash2 size={13} /></button></div></div>)}{!items.length && <p className="rounded-lg bg-[#f7f6fc] p-3 text-xs text-[#858592]">No hay préstamos pendientes.</p>}</div></div>; }

function ModalPago({ prestamo, cuentas, onCerrar, onConfirmar }: { prestamo: Prestamo; cuentas: Cuenta[]; onCerrar: () => void; onConfirmar: (id: string) => Promise<void> }) { const [cuenta, setCuenta] = useState(prestamo.cuenta_id ?? cuentas[0]?.id ?? ''); return <Modal titulo="Registrar pago" onCerrar={onCerrar}><p className="text-sm">Selecciona la cuenta del pago de {prestamo.persona}.</p><select value={cuenta} onChange={(event) => setCuenta(event.target.value)} className="campo mt-4">{cuentas.map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</select><button disabled={!cuenta} onClick={() => void onConfirmar(cuenta)} className="mt-4 w-full rounded-lg bg-[#293ea9] px-3 py-2 text-sm font-bold text-white disabled:opacity-40">Confirmar pago</button></Modal>; }
function ModalEdicion({ prestamo, onCerrar, onConfirmar }: { prestamo: Prestamo; onCerrar: () => void; onConfirmar: (datos: Pick<Prestamo, 'persona' | 'monto'>) => Promise<void> }) { const [persona, setPersona] = useState(prestamo.persona); const [monto, setMonto] = useState(String(prestamo.monto)); function enviar(event: FormEvent) { event.preventDefault(); void onConfirmar({ persona: persona.trim(), monto: Number(monto) }); } return <Modal titulo="Editar préstamo" onCerrar={onCerrar}><form onSubmit={enviar} className="space-y-3"><input required value={persona} onChange={(event) => setPersona(event.target.value)} className="campo" placeholder="Persona" /><input required min="0.01" step="0.01" type="number" value={monto} onChange={(event) => setMonto(event.target.value)} className="campo" /><button className="w-full rounded-lg bg-[#293ea9] px-3 py-2 text-sm font-bold text-white">Guardar cambios</button></form></Modal>; }
function Modal({ titulo, onCerrar, children }: { titulo: string; onCerrar: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-[#1d1d26]/45 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-xl bg-white p-5 shadow-2xl"><div className="mb-4 flex justify-between"><h3 className="font-bold">{titulo}</h3><button onClick={onCerrar} aria-label="Cerrar"><X size={18} /></button></div>{children}</div></div>; }
