import { Plus, X } from 'lucide-react';
import { FormEvent, useEffect, useRef, useState } from 'react';
import { Cuenta } from '@/tipos/movimientos';
import { DatosFormulario } from '@/componentes/FormularioMovimiento';

const categorias = ['Alimentación', 'Transporte', 'Entretenimiento', 'Cuidado personal', 'Gastos hormiga', 'Salud', 'Otro'];
type Props = { cuentas: Cuenta[]; alCerrar: () => void; alGuardar: (datos: DatosFormulario) => Promise<void>; onRegistroCompleto: () => void };

export function RegistroRapido({ cuentas, alCerrar, alGuardar, onRegistroCompleto }: Props) {
  const primeraCuenta = cuentas.find((cuenta) => cuenta.nombre.toLowerCase() === 'yape') ?? cuentas[0];
  const [monto, setMonto] = useState(''); const [categoria, setCategoria] = useState(categorias[0]); const [cuentaId, setCuentaId] = useState(primeraCuenta?.id ?? ''); const [concepto, setConcepto] = useState(''); const [mostrarConcepto, setMostrarConcepto] = useState(false); const referencia = useRef<HTMLInputElement>(null);
  useEffect(() => referencia.current?.focus(), []);
  async function enviar(evento: FormEvent) { evento.preventDefault(); if (Number(monto) <= 0 || !cuentaId) return; await alGuardar({ tipo: 'gasto', monto: Number(monto), fecha: new Date().toISOString().slice(0, 10), categoria, cuenta_id: cuentaId, concepto: concepto.trim() || categoria }); }
  return <div className="animate-overlay-in fixed inset-0 z-50 flex items-end bg-[#1d1d26]/45 backdrop-blur-sm" role="dialog" aria-modal="true" onClick={alCerrar}><div className="animate-modal-in w-full rounded-t-[24px] bg-white p-5 pb-[calc(1.25rem+env(safe-area-inset-bottom))]" onClick={(evento) => evento.stopPropagation()}><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-bold">Registro rápido</h2><button onClick={alCerrar} aria-label="Cerrar"><X size={21} /></button></div><form onSubmit={enviar} className="space-y-5"><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-lg text-[#777887]">S/</span><input ref={referencia} autoFocus type="number" inputMode="decimal" min="0.01" step="0.01" value={monto} onChange={(evento) => setMonto(evento.target.value)} className="w-full border-b-2 border-[#293ea9] bg-transparent py-2 pl-10 text-[32px] font-bold outline-none" placeholder="0.00" /></div><div><p className="mb-2 text-xs font-bold uppercase tracking-wider text-[#777887]">Categoría</p><div className="flex max-w-full gap-2 overflow-x-auto pb-1">{categorias.map((item) => <button type="button" key={item} onClick={() => setCategoria(item)} className={`shrink-0 rounded-full px-3 py-2 text-xs font-semibold ${categoria === item ? 'bg-[#293ea9] text-white' : 'bg-[#f0f0f6] text-[#555766]'}`}>{item}</button>)}</div></div><div><p className="mb-2 text-xs font-bold uppercase tracking-wider text-[#777887]">Cuenta</p><div className="flex gap-2 overflow-x-auto pb-1">{cuentas.map((cuenta) => <button type="button" key={cuenta.id} onClick={() => setCuentaId(cuenta.id)} className={`shrink-0 rounded-full px-3 py-2 text-xs font-semibold ${cuentaId === cuenta.id ? 'bg-[#293ea9] text-white' : 'bg-[#f0f0f6] text-[#555766]'}`}>{cuenta.nombre}</button>)}</div></div>{mostrarConcepto && <input value={concepto} onChange={(evento) => setConcepto(evento.target.value)} className="campo" placeholder="Concepto opcional" />}<button type="button" onClick={() => setMostrarConcepto((visible) => !visible)} className="flex items-center gap-1 text-xs font-semibold text-[#293ea9]"><Plus size={14} /> {mostrarConcepto ? 'Ocultar concepto' : 'Agregar concepto'}</button><button type="submit" className="h-13 w-full rounded-xl bg-[#293ea9] py-3 text-base font-bold text-white">Guardar</button></form><button onClick={onRegistroCompleto} className="mt-4 w-full text-center text-sm font-semibold text-[#293ea9]">Registro completo →</button></div></div>;
}
