import { ArrowDown, ArrowUp, CalendarDays, PiggyBank } from 'lucide-react';
import { ReactNode } from 'react';
import { ResumenFinanciero } from '@/tipos/movimientos';
import { moneda } from '@/utilidades/formato';

type Props = { resumen: ResumenFinanciero };

export function TarjetasResumen({ resumen }: Props) { return <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><TarjetaMetrica titulo="Ingresos totales" valor={moneda(resumen.ingresos)} detalle="vs quincena anterior" icono={<ArrowUp size={18} />} color="verde" insignia="↗ +12%" /><TarjetaMetrica titulo="Gastos totales" valor={moneda(resumen.gastos)} detalle={<><span>Fijos: {moneda(resumen.gastos * .67)}</span><i /> <span>Var: {moneda(resumen.gastos * .33)}</span></>} icono={<ArrowDown size={18} />} color="rojo" insignia="↘ control" /><TarjetaMetrica titulo="Ahorro neto" valor={moneda(resumen.ahorro)} detalle="Meta: S/ 3,000" icono={<PiggyBank size={18} />} color="azul" insignia={resumen.ahorro >= 0 ? '↗ positivo' : '↘ revisar'} progreso={Math.min(100, Math.max(0, (resumen.ahorro / 3000) * 100))} /><TarjetaMetrica titulo="Balance proyectado" valor={moneda(resumen.proyectado)} detalle="Estimado al cierre de mes" icono={<CalendarDays size={17} />} color="amarillo" insignia={resumen.proyectado >= 0 ? '↗ estable' : '↘ alerta'} /></section> }

function TarjetaMetrica({ titulo, valor, detalle, icono, color, insignia, progreso }: { titulo: string; valor: string; detalle: ReactNode; icono: ReactNode; color: 'verde' | 'rojo' | 'azul' | 'amarillo'; insignia?: string; progreso?: number }) { const colores = { verde: 'text-[#007c59] bg-[#e4faf1]', rojo: 'text-[#c52c2f] bg-[#fff0f0]', azul: 'text-[#293ea9] bg-[#eef0ff]', amarillo: 'text-[#aa7010] bg-[#fff4dc]' }; const tendencia = color === 'rojo' ? 'bg-[#fff0f0] text-[#c52c2f]' : 'bg-[#e5fbf1] text-[#00805e]'; return <div className={`relative overflow-hidden rounded-xl border border-[#dedde8] bg-white p-5 shadow-[0_2px_8px_rgba(29,29,38,.04)] ${color === 'amarillo' ? 'border-l-[3px] border-l-[#ffb43b]' : ''}`}><div className="flex items-center justify-between"><p className="text-xs font-bold tracking-wide text-[#646574]">{titulo}</p><span className={`grid h-8 w-8 place-items-center rounded-lg ${colores[color]}`}>{icono}</span></div><p className={`mt-3 text-[27px] font-bold tracking-[-1px] ${color === 'azul' ? 'text-[#293ea9]' : 'text-[#23232d]'}`}>{valor}</p><div className="mt-2 flex flex-wrap items-center gap-2 text-[11px] text-[#81818e]">{insignia && <span className={`rounded-md px-2 py-1 font-bold ${tendencia}`}>{insignia}</span>}{detalle}</div>{progreso !== undefined && <div className="absolute bottom-0 left-0 h-[3px] bg-[#293ea9]" style={{ width: `${progreso}%` }} />}</div> }
