import { ArrowDown, ArrowUp, CalendarDays, PiggyBank, TrendingDown, TrendingUp } from 'lucide-react';
import { ReactNode } from 'react';
import { ResumenFinanciero } from '@/tipos/movimientos';
import { moneda } from '@/utilidades/formato';

type Props = { resumen: ResumenFinanciero; ahorroAnterior?: number };
export function TarjetasResumen({ resumen, ahorroAnterior = 0 }: Props) {
  const ingresosMeta = Math.min(100, (resumen.ingresos / 3000) * 100);
  const gastosFijos = resumen.gastos * 0.67;
  const gastosVariables = resumen.gastos - gastosFijos;
  const ahorroCambio = resumen.ahorro - ahorroAnterior;
  const diasRestantes = new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0).getDate() - new Date().getDate();
  const promedioDiario = diasRestantes > 0 ? resumen.proyectado / diasRestantes : resumen.proyectado;
  return <section className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4"><Tarjeta titulo="Ingresos totales" valor={moneda(resumen.ingresos)} detalle="Meta mensual: S/ 3,000" icono={<ArrowUp size={18} />} color="verde" tooltip="Total de ingresos registrados en este período." insignia="↗ objetivo" extra={<div className="mt-3 h-2 overflow-hidden rounded-full bg-[#e8f6ef]"><div className="h-full rounded-full bg-[#10b981] transition-all duration-700" style={{ width: `${ingresosMeta}%` }} /></div>} /><Tarjeta titulo="Gastos totales" valor={moneda(resumen.gastos)} detalle={<><span>Fijos: {moneda(gastosFijos)}</span><span>Var: {moneda(gastosVariables)}</span></>} icono={<ArrowDown size={18} />} color="rojo" tooltip="Suma de todos tus gastos registrados." insignia="↘ control" extra={<div className="mt-3 flex h-2 overflow-hidden rounded-full bg-[#fff1df]"><div className="bg-[#293ea9]" style={{ width: `${resumen.gastos ? gastosFijos / resumen.gastos * 100 : 0}%` }} /><div className="bg-[#f2a944]" style={{ width: `${resumen.gastos ? gastosVariables / resumen.gastos * 100 : 0}%` }} /></div>} /><Tarjeta titulo="Ahorro neto" valor={moneda(resumen.ahorro)} detalle={<span>{ahorroCambio >= 0 ? `${moneda(ahorroCambio)} más que la quincena anterior` : `${moneda(Math.abs(ahorroCambio))} menos que la quincena anterior`}</span>} icono={ahorroCambio >= 0 ? <TrendingUp size={18} /> : <TrendingDown size={18} />} color="azul" tooltip="Ingresos menos gastos. Indica cuánto dinero has conservado." insignia={resumen.ahorro >= 0 ? '↗ positivo' : '↘ revisar'} /><Tarjeta titulo="Balance proyectado" valor={moneda(resumen.proyectado)} detalle={`Quedan ${diasRestantes} días. Promedio diario: ${moneda(promedioDiario)} disponible.`} icono={<CalendarDays size={17} />} color="amarillo" tooltip="Estimación de tu saldo disponible al cierre del mes." insignia={resumen.proyectado >= 0 ? '↗ estable' : '↘ alerta'} /></section>;
}

function Tarjeta({ titulo, valor, detalle, icono, color, tooltip, insignia, extra }: { titulo: string; valor: string; detalle: ReactNode; icono: ReactNode; color: 'verde' | 'rojo' | 'azul' | 'amarillo'; tooltip: string; insignia: string; extra?: ReactNode }) { const colores = { verde: 'text-[#007c59] bg-[#e4faf1]', rojo: 'text-[#c52c2f] bg-[#fff0f0]', azul: 'text-[#293ea9] bg-[#eef0ff]', amarillo: 'text-[#aa7010] bg-[#fff4dc]' }; return <article className="group relative overflow-visible rounded-xl border border-[#dedde8] bg-white p-5 shadow-[0_2px_8px_rgba(29,29,38,.04)] transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-center justify-between"><p className="text-xs font-bold tracking-wide text-[#646574]">{titulo}</p><span title={tooltip} className={`grid h-8 w-8 cursor-help place-items-center rounded-lg ${colores[color]}`}>{icono}</span></div><p className="mt-3 text-2xl font-bold text-[#23232d]">{valor}</p>{extra}<div className="mt-2 flex flex-wrap items-center gap-2 text-[11px] text-[#81818e]"><span className={`rounded-md px-2 py-1 font-bold ${color === 'rojo' ? 'bg-[#fff0f0] text-[#c52c2f]' : 'bg-[#e5fbf1] text-[#00805e]'}`}>{insignia}</span>{detalle}</div></article>; }
